export type AdapterUser = {
  id: string;
  name: string;
  email?: string | null;
  emailVerified?: Date | null;
  image?: string | null;
};

export const users: Array<AdapterUser> = [
  {
    id: '1',
    name: 'James Smith',
    email: 'james.smith@gmail.com',
    emailVerified: new Date('2025-01-03'),
    image: undefined,
  },
  {
    id: '2',
    name: 'Olivia Johnson',
    email: 'olivia.johnson@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '3',
    name: 'William Brown',
    email: 'william.brown@gmail.com',
    emailVerified: new Date('2025-01-05'),
    image: undefined,
  },
  {
    id: '4',
    name: 'Emma Garcia',
    email: 'emma.garcia@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '5',
    name: 'Benjamin Miller',
    email: 'benjamin.miller@gmail.com',
    emailVerified: new Date('2025-01-08'),
    image: undefined,
  },
  {
    id: '6',
    name: 'Sophia Davis',
    email: 'sophia.davis@gmail.com',
    emailVerified: new Date('2025-01-11'),
    image: undefined,
  },
  {
    id: '7',
    name: 'Lucas Martinez',
    email: 'lucas.martinez@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '8',
    name: 'Isabella Anderson',
    email: 'isabella.anderson@gmail.com',
    emailVerified: new Date('2025-01-14'),
    image: undefined,
  },
  {
    id: '9',
    name: 'Henry Thomas',
    email: 'henry.thomas@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '10',
    name: 'Charlotte Taylor',
    email: 'charlotte.taylor@gmail.com',
    emailVerified: new Date('2025-01-17'),
    image: undefined,
  },
  {
    id: '11',
    name: 'Alexander Moore',
    email: 'alexander.moore@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '12',
    name: 'Amelia Hernandez',
    email: 'amelia.hernandez@gmail.com',
    emailVerified: new Date('2025-01-19'),
    image: undefined,
  },
  {
    id: '13',
    name: 'Michael Jackson',
    email: 'michael.jackson@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '14',
    name: 'Evelyn White',
    email: 'evelyn.white@gmail.com',
    emailVerified: new Date('2025-01-21'),
    image: undefined,
  },
  {
    id: '15',
    name: 'Ethan Harris',
    email: 'ethan.harris@gmail.com',
    emailVerified: new Date('2025-01-22'),
    image: undefined,
  },
  {
    id: '16',
    name: 'Mia Clark',
    email: 'mia.clark@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '17',
    name: 'Daniel Lewis',
    email: 'daniel.lewis@gmail.com',
    emailVerified: new Date('2025-01-10'),
    image: undefined,
  },
  {
    id: '18',
    name: 'Luna Walker',
    email: 'luna.walker@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '19',
    name: 'Matthew Hall',
    email: 'matthew.hall@gmail.com',
    emailVerified: new Date('2025-01-09'),
    image: undefined,
  },
  {
    id: '20',
    name: 'Harper Allen',
    email: 'harper.allen@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '21',
    name: 'Joseph Young',
    email: 'joseph.young@gmail.com',
    emailVerified: new Date('2025-01-15'),
    image: undefined,
  },
  {
    id: '22',
    name: 'Scarlett King',
    email: 'scarlett.king@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '23',
    name: 'David Scott',
    email: 'david.scott@gmail.com',
    emailVerified: new Date('2025-01-23'),
    image: undefined,
  },
  {
    id: '24',
    name: 'Aurora Wright',
    email: 'aurora.wright@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '25',
    name: 'Samuel Green',
    email: 'samuel.green@gmail.com',
    emailVerified: new Date('2025-01-06'),
    image: undefined,
  },
  {
    id: '26',
    name: 'Lily Adams',
    email: 'lily.adams@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '27',
    name: 'Noah Baker',
    email: 'noah.baker@gmail.com',
    emailVerified: new Date('2025-01-07'),
    image: undefined,
  },
  {
    id: '28',
    name: 'Hannah Nelson',
    email: 'hannah.nelson@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '29',
    name: 'Elijah Hill',
    email: 'elijah.hill@gmail.com',
    emailVerified: new Date('2025-01-18'),
    image: undefined,
  },
  {
    id: '30',
    name: 'Zoe Carter',
    email: 'zoe.carter@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '31',
    name: 'Aiden Roberts',
    email: 'aiden.roberts@gmail.com',
    emailVerified: new Date('2025-01-04'),
    image: undefined,
  },
  {
    id: '32',
    name: 'Ellie Mitchell',
    email: 'ellie.mitchell@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '33',
    name: 'Jacob Perez',
    email: 'jacob.perez@gmail.com',
    emailVerified: new Date('2025-01-05'),
    image: undefined,
  },
  {
    id: '34',
    name: 'Violet Campbell',
    email: 'violet.campbell@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '35',
    name: 'Mason Rodriguez',
    email: 'mason.rodriguez@gmail.com',
    emailVerified: new Date('2025-01-08'),
    image: undefined,
  },
  {
    id: '36',
    name: 'Aria Turner',
    email: 'aria.turner@gmail.com',
    emailVerified: new Date('2025-01-11'),
    image: undefined,
  },
  {
    id: '37',
    name: 'Logan Phillips',
    email: 'logan.phillips@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '38',
    name: 'Penelope Parker',
    email: 'penelope.parker@gmail.com',
    emailVerified: new Date('2025-01-14'),
    image: undefined,
  },
  {
    id: '39',
    name: 'Sebastian Evans',
    email: 'sebastian.evans@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '40',
    name: 'Nora Edwards',
    email: 'nora.edwards@gmail.com',
    emailVerified: new Date('2025-01-17'),
    image: undefined,
  },
  {
    id: '41',
    name: 'Jack Collins',
    email: 'jack.collins@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '42',
    name: 'Chloe Rivera',
    email: 'chloe.rivera@gmail.com',
    emailVerified: new Date('2025-01-19'),
    image: undefined,
  },
  {
    id: '43',
    name: 'Leo Simmons',
    email: 'leo.simmons@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '44',
    name: 'Grace Morris',
    email: 'grace.morris@gmail.com',
    emailVerified: new Date('2025-01-21'),
    image: undefined,
  },
  {
    id: '45',
    name: 'Owen Ward',
    email: 'owen.ward@gmail.com',
    emailVerified: new Date('2025-01-22'),
    image: undefined,
  },
  {
    id: '46',
    name: 'Elizabeth Morgan',
    email: 'elizabeth.morgan@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '47',
    name: 'Jackson Peterson',
    email: 'jackson.peterson@gmail.com',
    emailVerified: new Date('2025-01-10'),
    image: undefined,
  },
  {
    id: '48',
    name: 'Madison Cook',
    email: 'madison.cook@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '49',
    name: 'Gabriel Stewart',
    email: 'gabriel.stewart@gmail.com',
    emailVerified: new Date('2025-01-09'),
    image: undefined,
  },
  {
    id: '50',
    name: 'Layla Bell',
    email: 'layla.bell@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '51',
    name: 'Carter Cooper',
    email: 'carter.cooper@gmail.com',
    emailVerified: new Date('2025-01-15'),
    image: undefined,
  },
  {
    id: '52',
    name: 'Elliana Reed',
    email: 'elliana.reed@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '53',
    name: 'Wyatt Bailey',
    email: 'wyatt.bailey@gmail.com',
    emailVerified: new Date('2025-01-23'),
    image: undefined,
  },
  {
    id: '54',
    name: 'Stella Sanders',
    email: 'stella.sanders@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '55',
    name: 'Julian Price',
    email: 'julian.price@gmail.com',
    emailVerified: new Date('2025-01-06'),
    image: undefined,
  },
  {
    id: '56',
    name: 'Aubrey Russell',
    email: 'aubrey.russell@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '57',
    name: 'Grayson Cox',
    email: 'grayson.cox@gmail.com',
    emailVerified: new Date('2025-01-07'),
    image: undefined,
  },
  {
    id: '58',
    name: 'Victoria Hayes',
    email: 'victoria.hayes@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '59',
    name: 'Isaac Foster',
    email: 'isaac.foster@gmail.com',
    emailVerified: new Date('2025-01-18'),
    image: undefined,
  },
  {
    id: '60',
    name: 'Savannah Bryant',
    email: 'savannah.bryant@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '61',
    name: 'Anthony Howard',
    email: 'anthony.howard@gmail.com',
    emailVerified: new Date('2025-01-03'),
    image: undefined,
  },
  {
    id: '62',
    name: 'Natalie Jenkins',
    email: 'natalie.jenkins@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '63',
    name: 'Dylan Wood',
    email: 'dylan.wood@gmail.com',
    emailVerified: new Date('2025-01-05'),
    image: undefined,
  },
  {
    id: '64',
    name: 'Hazel Hughes',
    email: 'hazel.hughes@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '65',
    name: 'Caleb Murphy',
    email: 'caleb.murphy@gmail.com',
    emailVerified: new Date('2025-01-08'),
    image: undefined,
  },
  {
    id: '66',
    name: 'Eliana Brooks',
    email: 'eliana.brooks@gmail.com',
    emailVerified: new Date('2025-01-11'),
    image: undefined,
  },
  {
    id: '67',
    name: 'Nathan Gray',
    email: 'nathan.gray@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '68',
    name: 'Ruby Foster',
    email: 'ruby.foster@gmail.com',
    emailVerified: new Date('2025-01-14'),
    image: undefined,
  },
  {
    id: '69',
    name: 'Andrew Kelly',
    email: 'andrew.kelly@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '70',
    name: 'Bella Bennett',
    email: 'bella.bennett@gmail.com',
    emailVerified: new Date('2025-01-17'),
    image: undefined,
  },
  {
    id: '71',
    name: 'Ryan Ward',
    email: 'ryan.ward@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '72',
    name: 'Willow Morales',
    email: 'willow.morales@gmail.com',
    emailVerified: new Date('2025-01-19'),
    image: undefined,
  },
  {
    id: '73',
    name: 'Luke Barnes',
    email: 'luke.barnes@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '74',
    name: 'Lucy Ross',
    email: 'lucy.ross@gmail.com',
    emailVerified: new Date('2025-01-21'),
    image: undefined,
  },
  {
    id: '75',
    name: 'Christopher Myers',
    email: 'christopher.myers@gmail.com',
    emailVerified: new Date('2025-01-22'),
    image: undefined,
  },
  {
    id: '76',
    name: 'Eleanor Powell',
    email: 'eleanor.powell@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '77',
    name: 'Joshua Long',
    email: 'joshua.long@gmail.com',
    emailVerified: new Date('2025-01-10'),
    image: undefined,
  },
  {
    id: '78',
    name: 'Autumn Patterson',
    email: 'autumn.patterson@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '79',
    name: 'Hunter Torres',
    email: 'hunter.torres@gmail.com',
    emailVerified: new Date('2025-01-09'),
    image: undefined,
  },
  {
    id: '80',
    name: 'Sadie Reed',
    email: 'sadie.reed@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '81',
    name: 'Jonathan Sanders',
    email: 'jonathan.sanders@gmail.com',
    emailVerified: new Date('2025-01-15'),
    image: undefined,
  },
  {
    id: '82',
    name: 'Violet Cook',
    email: 'violet.cook@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '83',
    name: 'Thomas Lee',
    email: 'thomas.lee@gmail.com',
    emailVerified: new Date('2025-01-23'),
    image: undefined,
  },
  {
    id: '84',
    name: 'Naomi Murphy',
    email: 'naomi.murphy@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '85',
    name: 'Evan Rivera',
    email: 'evan.rivera@gmail.com',
    emailVerified: new Date('2025-01-06'),
    image: undefined,
  },
  {
    id: '86',
    name: 'Caroline Bennett',
    email: 'caroline.bennett@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '87',
    name: 'Charles Bell',
    email: 'charles.bell@gmail.com',
    emailVerified: new Date('2025-01-07'),
    image: undefined,
  },
  {
    id: '88',
    name: 'Lillian Watson',
    email: 'lillian.watson@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '89',
    name: 'Isaiah Bryant',
    email: 'isaiah.bryant@gmail.com',
    emailVerified: new Date('2025-01-18'),
    image: undefined,
  },
  {
    id: '90',
    name: 'Madeline Cox',
    email: 'madeline.cox@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '91',
    name: 'Aaron Kelly',
    email: 'aaron.kelly@gmail.com',
    emailVerified: new Date('2025-01-03'),
    image: undefined,
  },
  {
    id: '92',
    name: 'Samantha Brooks',
    email: 'samantha.brooks@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '93',
    name: 'Connor Mitchell',
    email: 'connor.mitchell@gmail.com',
    emailVerified: new Date('2025-01-05'),
    image: undefined,
  },
  {
    id: '94',
    name: 'Alice Peterson',
    email: 'alice.peterson@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '95',
    name: 'Ezra Ross',
    email: 'ezra.ross@gmail.com',
    emailVerified: new Date('2025-01-08'),
    image: undefined,
  },
  {
    id: '96',
    name: 'Anna Simmons',
    email: 'anna.simmons@gmail.com',
    emailVerified: new Date('2025-01-11'),
    image: undefined,
  },
  {
    id: '97',
    name: 'Levi Powell',
    email: 'levi.powell@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '98',
    name: 'Maya Jenkins',
    email: 'maya.jenkins@gmail.com',
    emailVerified: new Date('2025-01-14'),
    image: undefined,
  },
  {
    id: '99',
    name: 'Caleb Russell',
    email: 'caleb.russell@gmail.com',
    emailVerified: null,
    image: undefined,
  },
  {
    id: '100',
    name: 'Audrey Price',
    email: 'audrey.price@gmail.com',
    emailVerified: new Date('2025-01-20'),
    image: undefined,
  },
];
